name: Build & Test

on:
    push:
        branches: ["main", "rel-*"]

env:
    NAME: Sagar Bera

jobs:
    build:
        runs-on: ubuntu-20.04

        timeout-minutes: 5

        steps:
            - name: Greet user
              run: echo "Hello $NAME"

            - name: Another step
              run: echo "This is another step in the same job"

    test:
        runs-on: ubuntu-22.04

        timeout-minutes: 10

        needs: build

        env:
            NAME: Planet

        strategy:
            matrix:
                browser: [chrome, firefox]
                device: [desktop, mobile]

        steps:
            - name: Step inside test job
              run: echo "Hello $NAME"

            - name: Another step
              run: echo "This is another step in the same job"

            - name: Demo of how to access current matrix context
              run: |
                  echo "Browser:" ${{ matrix.browser }}
                  echo "Device: ${{ matrix.device }}"
